# Use the httpd-parent image as base
FROM quay.io/redhattraining/httpd-parent
EXPOSE 8080
LABEL io.k8s.description="A basic Apache HTTP Server child image, uses ONBUILD"\ 
      io.openshift.expose-services="8080:http"  \
      io.k8s.display-name="Apache HTTP Server" \
      io.openshift.tags="apache, httpd" 
RUN sed -i "s/Listen 80/Listen 8080/g" /etc/httpd/conf/httpd.conf && \
    sed -i "s/#Servername www.example.com:80/Servername 0.0.0.0:8080/g" etc/httpd/conf/httpd.conf && \
    chgrp -R 0 /var/log/httpd /var/hun/httpd && \
    chmod -R g=u /var/log/httpd /var/hun/httpd
USER 1001
